// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20200821230635_modelbuilder")]
    partial class modelbuilder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Temperament")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Color = "Black",
                            Description = "testDesc",
                            Name = "Cat1",
                            Temperament = "Calm"
                        },
                        new
                        {
                            CatId = 2,
                            Color = "Tan",
                            Description = "testDesc",
                            Name = "Cat2",
                            Temperament = "Anxious"
                        },
                        new
                        {
                            CatId = 3,
                            Color = "White",
                            Description = "testDesc",
                            Name = "Cat3",
                            Temperament = "Hyper"
                        },
                        new
                        {
                            CatId = 4,
                            Color = "Cream",
                            Description = "testDesc",
                            Name = "Cat4",
                            Temperament = "Energetic"
                        },
                        new
                        {
                            CatId = 5,
                            Color = "Black",
                            Description = "testDesc",
                            Name = "Cat5",
                            Temperament = "lazy"
                        });
                });

            modelBuilder.Entity("AnimalShelterApi.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Temperament")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Color = "Black",
                            Description = "testDesc",
                            Name = "Dog1",
                            Temperament = "Calm"
                        },
                        new
                        {
                            DogId = 2,
                            Color = "Tan",
                            Description = "testDesc",
                            Name = "Dog2",
                            Temperament = "Anxious"
                        },
                        new
                        {
                            DogId = 3,
                            Color = "White",
                            Description = "testDesc",
                            Name = "Dog3",
                            Temperament = "Hyper"
                        },
                        new
                        {
                            DogId = 4,
                            Color = "Cream",
                            Description = "testDesc",
                            Name = "Dog4",
                            Temperament = "Energetic"
                        },
                        new
                        {
                            DogId = 5,
                            Color = "Black",
                            Description = "testDesc",
                            Name = "Dog5",
                            Temperament = "lazy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
